### ISSUE TITLE
Bug: Missing Info - Not all graphs display data for set point and hold point.

### ISSUE THREAD

**Issue by aliriddle** [MindrustUK/Heatmiser-for-home-assistant#177] opened 2024-10-13 07:35 UTC
![image](https://github.com/user-attachments/assets/fe0c5a01-5a99-4b25-ba09-9c44574fadb7)

I'm not sure when/version I created these history charts, but only one of them shows when the hold and target temps have been activated. 

I'm using the dev branch 2.0.0

**Comment by aliriddle** [comment] 2024-10-13 07:36
I'm sure they were default charts, and can't find options to enable the missing data.

**Comment by MindrustUK** [comment] 2024-10-13 13:41
It looks like your lounge is working as expected from the pictures. These are default graphs, there's nothing special done to create them. I've checked my dev instance and the data appears fine? I.e. I can see observed and target temperatures as constant appearances on the graph. What type of devices are the master bedroom and kitchen? Are they Neostats, air temperature sensors or something else?

**Comment by aliriddle** [comment] 2024-10-13 14:26
My current setup details are below. Separately I updated to the Dev branch a few months ago, and don’t believe it’s updated since. Do I have to delete and reinstall through the SSH mechanism to get the latest version?neoHub Firmware Version: v2110
App Version: 3.0.65
Kitchen
Device Type: neoStat v2
Firmware: v29
Connection Status: Online
Lounge
Device Type: neoAir v2
Firmware: V184
Connection Status: Online
Master Bedroom
Device Type: neoAir v2
Firmware: v184
Connection Status: Online
Ali Bathroom
Device Type: neoStat v2
Firmware: v35
Connection Status: Online

**Comment by MindrustUK** [comment] 2024-10-13 15:07
I still can't see anything obviously wrong here, I suggest you delete and re-install and see if this clears out any weird behaviour, given what you've said maybe something has ended up in a bad state somewhere.

**Comment by aliriddle** [comment] 2024-10-18 15:51
Ive disabled and tried to delete  the integration using the top right corner and  3 dots delete , but it still shows in file browser and when I try and use the file browser to delete the integration I get the following error:

￼

Is there another easy way to delete? That way I can resinatll latest dev branch

Many Thanks

Alastair

**Comment by aliriddle** [comment] 2024-10-18 16:11
Hi,

All sorted, managed to find the SSH command to delete.

All updated, will test over the weekend. 

Alastair

**Comment by aliriddle** [comment] 2024-10-20 07:19
Hi,So the ability to set a hold time seems to be broken since I updated. Previously I had automations that what set a hold for 30 minutes at a set temperature when conviction’s were met. I can see that automations trigger but the resulting hold signal never seems to make it to the thermostats.Also the default graphs still don’t appear to show the shaded colouring when the hold is on. (Even when I set the hold manually using the offal Heatmiser app)If you need any more details or have any ideas let me know.

**Comment by aliriddle** [comment] 2024-10-20 09:20
Ive reverted back to an older backup prior to when i updated to the latest Dev Branch, and functionality returned.

**Comment by MindrustUK** [comment] 2024-10-20 14:06
The hold functionality has been cut back in version 1.5 as per the release notes.

As to hold not triggering there is a bug to do with types not being correctly interpreted here: https://github.com/MindrustUK/Heatmiser-for-home-assistant/issues/185 this maybe part of your issue.

I'll investigate the graphing issue when I get a chance.

**Comment by aliriddle** [comment] 2024-10-20 18:42
Thanks for update. I presume switching from Dev branch back to 1.5 may make the best sense for now then?

**Comment by MindrustUK** [comment] 2024-10-21 16:33
@aliriddle You're bug is an odd one, I can't really recommend a course of action as I don't quite understand where the issue is coming from for now, I need some time to investigate this properly before I can give you anything solid on why the graph isn't as expected. There is some additional hold stuff coming to 1.5 to re-enable the old style hold logic so you might want to keep an eye on that.

**Comment by aliriddle** [comment] 2024-10-21 16:42
No problem. 

I've deleted heatmiserneo folder from the custom components folder, and installed the version via HACS.

I was expecting this to be 1.5, but is still showing 2.0.0. Not sure what's going on there. 

However, doing this I have control of hold timers again. But graphs remain non shaded.

I'll leave you to investigate the graphs, and report back if anything changes.

**Comment by MindrustUK** [comment] 2024-10-21 16:46
@aliriddle the 1.5 vs 2.0.0 is my fault, I forgot to change the manifest when I forked 1.5 (doing everything in a rush for this project at present) I figured if I changed it after the fact it might cause chaos so the first release of 2.0.0 will probably be 2.1.0. Totally my bad this one.

**Comment by aliriddle** [comment] 2024-10-21 16:52
No probs, I'm new to HA so it could have been just as likely a mistake I was making.

**Comment by ocrease** [comment] 2024-11-01 23:42
@aliriddle I wonder if its worth testing this on the latest dev branch. I've never seen this happen (on any branch), but there have been a lot of changes on the dev branch (none that I think would fix this though), so it might be worth a try if you are up for it.

**Comment by MindrustUK** [comment] 2024-11-02 16:20
I'd second this, so far I've been unable to replicate. Given how substantial the changes have been of late this may have just gotten fixed as an artefact of pulling the code into a much better state. Please test and let us know.

**Comment by aliriddle** [comment] 2024-11-02 19:34
Will do Sent from my iPhoneOn 2 Nov 2024, at 20:20, MindrustUK ***@***.***> wrote:﻿
I'd second this, so far I've been unable to replicate. Given how substantial the changes have been of late this may have just gotten fixed as an artefact of pulling the code into a much better state. Please test and let us know.

**Comment by MindrustUK** [comment] 2024-11-15 10:51
@aliriddle Any updates on this one?

**Comment by aliriddle** [comment] 2024-11-15 12:38
Just had a check now, and no change. I’m still very happy with functionality though, so effort is appreciated. Sent from my iPhoneOn 15 Nov 2024, at 10:51, MindrustUK ***@***.***> wrote:﻿
@aliriddle Any updates on this one?

**Comment by ocrease** [comment] 2024-11-15 17:08
@aliriddle Are you on the latest dev branch? I would suggest updating to the latest dev branch (if you haven't done so already) and the delete and re-add the integration entry.

To download the latest pre-release version using HACS. Don't forget to restart HA
![Redownload](https://github.com/user-attachments/assets/6a69e6d4-5497-46d2-af5c-b896efc766d0)

To delete the entry and re-add.
![DeleteReinstall](https://github.com/user-attachments/assets/42011798-6f9a-40bb-a650-64181e3cdbc9)

**Comment by aliriddle** [comment] 2024-11-15 21:49
Yep,That was me testing a hold temperature. Sent from my iPhoneOn 15 Nov 2024, at 17:08, ocrease ***@***.***> wrote:﻿
@aliriddle Are you on the latest dev branch? I would suggest updating to the latest dev branch (if you haven't done so already) and the delete and re-add the integration entry.
To download the latest pre-release version using HACS. Don't forget to restart HA
Redownload.gif (view on web)
To delete the entry and re-add.
DeleteReinstall.gif (view on web)

**Comment by MindrustUK** [comment] 2024-11-19 14:01
Hi @aliriddle 

I've tested on release 3.0.0beta4 with the following results:

This is a Heatmiser Neostat V2 with a floor probe sensor for electric underfloor heating:

![image](https://github.com/user-attachments/assets/6df4ebac-6ad7-4006-9fce-ed2346818798)


This is a Heatmiser Neostat V1 with no additional probes:

![image](https://github.com/user-attachments/assets/40d430b5-2bb7-47ef-8a38-49d825cc7927)

It looks like everything is working as expected. Can you check with the latest beta and let us know how you get on?

**Comment by aliriddle** [comment] 2024-11-19 14:21
￼

Seems to be the same, tracks current temp, and target temp, but no area under the graph filled in.

**Comment by MindrustUK** [comment] 2024-11-19 14:23
Sorry @aliriddle I don't think your screenshot made it in correctly?

**Comment by aliriddle** [comment] 2024-11-19 14:25
￼￼

**Comment by ocrease** [comment] 2024-11-19 14:49
@aliriddle, I suspect something went wrong during your previous installs of the dev branch. Have you deleted the hub like I suggested in an earlier post? Delete it, restart HA, verify you no longer have any entities related to the integration, then re-add the hub.

**Comment by aliriddle** [comment] 2024-11-19 18:29
Yeah, I had tried that, just tried again, still the same.

**Comment by ocrease** [comment] 2024-11-19 18:47
@aliriddle could you download diagnostics (accesible from the integration details or any of the device details) and upload them here?

**Comment by aliriddle** [comment] 2024-11-19 18:52
Will do, I'm very much aware it's probably something I'm doing wrong/individual issue. But I can't work out what's causing the issue. I’ll try uploading diagnostics soon. Sent from my iPhoneOn 19 Nov 2024, at 18:47, ocrease ***@***.***> wrote:﻿
@aliriddle could you download diagnostics (accesible from the integration details or any of the device details) and upload them here?

**Comment by aliriddle** [comment] 2024-11-19 19:26
￼

**Comment by ocrease** [comment] 2024-11-20 05:06
@aliriddle was your previous comment an attempt to upload the diagnostics? I think you are replying to this thread via email? It looks email attachments are not added to the issue which explains why we can't see your screenshots or diagnostics. Could you upload them directly on the github Web UI?

**Comment by aliriddle** [comment] 2024-11-20 09:53
[config_entry-heatmiserneo-01JD2TVQD6Y2YHK7X0R9EVWDPE.json](https://github.com/user-attachments/files/17828540/config_entry-heatmiserneo-01JD2TVQD6Y2YHK7X0R9EVWDPE.json)

**Comment by ocrease** [comment] 2024-11-20 13:15
@aliriddle thanks, unfortunately it all looks normal. Well, I did notice all of them are on Standby, is that what you expected? Not that it would affect the display on the history chart.

Could you go to Developer Tools -> Template and copy the output of this template?
```
{% for state in states.climate %}
========================
{{state.entity_id}}
State: {{state.state}}
{% for attr in state.attributes %}
{{attr}}: {{state_attr(state.entity_id, attr)}}{% endfor %}
{%endfor%}
```

Also could you try using the history chart card directly. Something like this:

![IMG_7871](https://github.com/user-attachments/assets/8dee901e-c257-44bb-bf45-fd74bac9e030)

**Comment by aliriddle** [comment] 2024-11-20 20:17
========================
climate.ali_bathroom
State: off

hvac_modes: [<HVACMode.OFF: 'off'>, <HVACMode.HEAT: 'heat'>]
min_temp: 5
max_temp: 35
target_temp_step: 1.0
preset_modes: ['home', 'boost', 'away']
current_temperature: 17.2
temperature: 12.0
hvac_action: off
preset_mode: home
device_type: 12
low_battery: False
offline: False
standby: True
hold_on: False
hold_time: 0:00
hold_temp: 21
floor_temperature: 127
preheat_active: False
hc_mode: HEATING
sensor_mode: None
friendly_name: Ali Bathroom
supported_features: 401

========================
climate.kitchen
State: off

hvac_modes: [<HVACMode.OFF: 'off'>, <HVACMode.HEAT: 'heat'>]
min_temp: 5
max_temp: 35
target_temp_step: 1.0
preset_modes: ['home', 'boost', 'away']
current_temperature: 19.2
temperature: 12.0
hvac_action: off
preset_mode: home
device_type: 12
low_battery: False
offline: False
standby: True
hold_on: False
hold_time: 0:00
hold_temp: 17
floor_temperature: 17
preheat_active: False
hc_mode: HEATING
sensor_mode: None
friendly_name: Kitchen
supported_features: 401

========================
climate.lounge
State: off

hvac_modes: [<HVACMode.OFF: 'off'>, <HVACMode.HEAT: 'heat'>]
min_temp: 5
max_temp: 35
target_temp_step: 1.0
preset_modes: ['home', 'boost', 'away']
current_temperature: 23.1
temperature: 12.0
hvac_action: off
preset_mode: home
device_type: 13
low_battery: False
offline: False
standby: True
hold_on: False
hold_time: 0:00
hold_temp: 21
floor_temperature: 127
preheat_active: False
hc_mode: VENT
sensor_mode: None
friendly_name: Lounge
supported_features: 401

========================
climate.master_bedroom
State: off

hvac_modes: [<HVACMode.OFF: 'off'>, <HVACMode.HEAT: 'heat'>]
min_temp: 5
max_temp: 35
target_temp_step: 1.0
preset_modes: ['home', 'boost', 'away']
current_temperature: 22.5
temperature: 12.0
hvac_action: off
preset_mode: home
device_type: 13
low_battery: False
offline: False
standby: True
hold_on: False
hold_time: 0:00
hold_temp: 28
floor_temperature: 127
preheat_active: False
hc_mode: VENT
sensor_mode: None
friendly_name: Master Bedroom
supported_features: 401
This template listens for the following state changed events:

Domain: climate
Entity: climate.ali_bathroom
Entity: climate.kitchen
Entity: climate.lounge
Entity: climate.master_bedroom

**Comment by aliriddle** [comment] 2024-11-20 20:37
Hi,

I think I’ve worked it out, as I almost exclusively use the hold function, despite heating, the graph doesn’t fill in the colour.

 Switching the thermostat to a set temperature in heat mode does trigger the fill on the graph.  

The behaviour I was expecting, was that when a hold temperature and duration is set, it would trigger the heating on “graph fill”

**Comment by ocrease** [comment] 2024-11-21 11:47
@aliriddle it's worth investigating. Could you take diagnostics and the output of the template from my earlier post when your heating is on the way you normally do it (eg via the hold function)?

**Comment by aliriddle** [comment] 2024-11-21 11:52
Result
Result type: string
========================
climate.ali_bathroom
State: off

hvac_modes: [<HVACMode.OFF: 'off'>, <HVACMode.HEAT: 'heat'>]
min_temp: 5
max_temp: 35
target_temp_step: 1.0
preset_modes: ['home', 'boost', 'away']
current_temperature: 16.0
temperature: 35.0
hvac_action: off
preset_mode: boost
device_type: 12
low_battery: False
offline: False
standby: True
hold_on: True
hold_time: 0:30
hold_temp: 35
floor_temperature: 127
preheat_active: False
hc_mode: HEATING
sensor_mode: None
friendly_name: Ali Bathroom
supported_features: 401

========================
climate.kitchen
State: off

hvac_modes: [<HVACMode.OFF: 'off'>, <HVACMode.HEAT: 'heat'>]
min_temp: 5
max_temp: 35
target_temp_step: 1.0
preset_modes: ['home', 'boost', 'away']
current_temperature: 17.9
temperature: 32.0
hvac_action: off
preset_mode: boost
device_type: 12
low_battery: False
offline: False
standby: True
hold_on: True
hold_time: 0:29
hold_temp: 32
floor_temperature: 16
preheat_active: False
hc_mode: HEATING
sensor_mode: None
friendly_name: Kitchen
supported_features: 401

========================
climate.lounge
State: off

hvac_modes: [<HVACMode.OFF: 'off'>, <HVACMode.HEAT: 'heat'>]
min_temp: 5
max_temp: 35
target_temp_step: 1.0
preset_modes: ['home', 'boost', 'away']
current_temperature: 19.8
temperature: 35.0
hvac_action: off
preset_mode: boost
device_type: 13
low_battery: False
offline: False
standby: True
hold_on: True
hold_time: 0:30
hold_temp: 35
floor_temperature: 127
preheat_active: False
hc_mode: VENT
sensor_mode: None
friendly_name: Lounge
supported_features: 401

========================
climate.master_bedroom
State: off

hvac_modes: [<HVACMode.OFF: 'off'>, <HVACMode.HEAT: 'heat'>]
min_temp: 5
max_temp: 35
target_temp_step: 1.0
preset_modes: ['home', 'boost', 'away']
current_temperature: 20.5
temperature: 12.0
hvac_action: off
preset_mode: boost
device_type: 13
low_battery: False
offline: False
standby: True
hold_on: True
hold_time: 0:30
hold_temp: 35
floor_temperature: 127
preheat_active: False
hc_mode: VENT
sensor_mode: None
friendly_name: Master Bedroom
supported_features: 401
This template listens for the following state changed events:

Domain: climate
Entity: climate.ali_bathroom
Entity: climate.kitchen
Entity: climate.lounge
Entity: climate.master_bedroom

**Comment by ocrease** [comment] 2024-11-21 12:03
@aliriddle Thanks, that's helpful. I see that your thermostats are still in standby, but are heating. There is a change we could try that might fix it, but I won't be able to try until mid to late next week.

I assume you turned on the heating from the heatmiser app rather than from HA?

**Comment by aliriddle** [comment] 2024-11-21 12:07
Correct, I used the Heatmiser app to set a 30 min Hold at a set temp.

As the electric underfloor is a secondary heat for our house (we have rads and central heating for daily heating), we only use the electric underfloor when electricity prices are low, with automations setup in HA to start a hold when prices fall below 7p/kwh

Thanks for looking into this. 

Ali

**Comment by ocrease** [comment] 2024-11-21 17:58
@aliriddle thanks for sharing the background. I think the bug is to do with the fact that your thermostats are in standby, rather than your use of the hold function. One simple way to fix/workaround this issue is to set a profile on the thermostats to a constant low temperature (could be the same as the 12c frost temperature) and then use hold from there. Your experience would be the same as what you currently have.

Another suggestion, rather than using hold, why don't you just set the temperature of the thermostat via an automation. I assume you can't know in advance how long prices will be under 7p/kwh, so an automation could increase the actual set temperature rather then the hold temperature when the price drops below your threshold and then reduce the set temperature when the prices increase above the threshold.

**Comment by ocrease** [comment] 2024-11-28 00:39
@aliriddle @MindrustUK this is hopefully fixed in #220

**Comment by aliriddle** [comment] 2024-11-28 07:21
I’ll keep and look out Sent from my iPhoneOn 28 Nov 2024, at 00:39, ocrease ***@***.***> wrote:﻿
@aliriddle @MindrustUK this is hopefully fixed in #220

**Comment by ocrease** [comment] 2024-11-29 23:17
@aliriddle the fix is merged into the pre release branch now. Let us know how it goes.

**Comment by aliriddle** [comment] 2024-11-30 07:03
Just had a quick test, and it seems to be fixedSent from my iPhoneOn 29 Nov 2024, at 23:17, ocrease ***@***.***> wrote:﻿
@aliriddle the fix is merged into the pre release branch now. Let us know how it goes.

**Comment by ocrease** [comment] 2024-12-04 19:18
@aliriddle how's it looking? Can this issue be closed now?

**Comment by aliriddle** [comment] 2024-12-04 19:21
I think so, looks good now

**Comment by ocrease** [comment] 2024-12-04 19:26
@aliriddle good to hear.

@MindrustUK I think you can close

**Comment by aliriddle** [comment] 2024-12-04 19:40
Thanks for the fix

**Closed as completed** 2024-12-06 16:37 UTC
Labels: bug
