### ISSUE TITLE
New Home Assistant User and Setup

### ISSUE THREAD

**Issue by aliriddle** [MindrustUK/Heatmiser-for-home-assistant#167] opened 2024-08-24 13:52 UTC
In the logs I'm getting this error:

This error originated from a custom integration.

Logger: custom_components.heatmiserneo.climate
Source: custom_components/heatmiserneo/climate.py:336
integration: Heatmiser Neo Climate (documentation)
First occurred: 14:03:44 (3 occurrences)
Last logged: 14:45:03

Lounge : Executing set_hold() with duration: {'hours': 0, 'minutes': 30, 'seconds': 0}, temperature: 26
Lounge : Executing set_hold() with duration: {'hours': 0, 'minutes': 30, 'seconds': 0}, temperature: 25

----

Ive setup an automation,to detect a price drop in electricity rate and to set a 30 min raised temp hold, with an associated push notification to show that it runs. 

I get the alert but am not seeing the associated hold on the thermostats.

**Comment by MindrustUK** [comment] 2024-08-26 11:25
Hi @aliriddle Thanks for the report. Are you using the master or dev branch? I'd suggest switching to dev if you're not using it already, due to a lack of time on my part I'm focusing my efforts onto dev with a aim to promote this as soon as possible to master.

If you are on the dev branch already after you've confirmed I'll find some time to do more investigation.

**Comment by aliriddle** [comment] 2024-08-26 11:38
I shall try that, thank you. I’m completely new and learning quickly, but I’ve not had to switch branch before in home assistant. Is this easily done? Sent from my iPhoneOn 26 Aug 2024, at 12:25, MindrustUK ***@***.***> wrote:﻿
Hi @aliriddle Thanks for the report. Are you using the master or dev branch? I'd suggest switching to dev if you're not using it already, due to a lack of time on my part I'm focusing my efforts onto dev with a aim to promote this as soon as possible to master.
If you are on the dev branch already after you've confirmed I'll find some time to do more investigation.

**Comment by MindrustUK** [comment] 2024-08-26 11:41
Instructions here should be accurate:

https://github.com/MindrustUK/Heatmiser-for-home-assistant/blob/dev/README.md

The important thing to note is the -b `git clone -b dev` let me know how you get on.

**Comment by aliriddle** [comment] 2024-08-26 12:03
Perfect thank you. Ver 2.0.0 now installed. Interestingly one of my thermostats now isn’t found. In the Heatmiser app they all show as online, but the neoStat v2 with firmware v25  (Ali Bath) is not showing.Sent from my iPhoneOn 26 Aug 2024, at 12:41, MindrustUK ***@***.***> wrote:﻿
Instructions here should be accurate:
https://github.com/MindrustUK/Heatmiser-for-home-assistant/blob/dev/README.md
The important thing to note is the -b git clone -b dev let me know how you get on.

**Comment by aliriddle** [comment] 2024-08-26 12:04
Nevermind it seems to have appeared now.I’ll have a play around over the next few days. Many ThanksAlastairSent from my iPhoneOn 26 Aug 2024, at 12:41, MindrustUK ***@***.***> wrote:﻿
Instructions here should be accurate:
https://github.com/MindrustUK/Heatmiser-for-home-assistant/blob/dev/README.md
The important thing to note is the -b git clone -b dev let me know how you get on.

**Comment by MindrustUK** [comment] 2024-08-28 11:23
Closing complete. Feel free to raise additional requests as needed.

**Closed by MindrustUK** 2024-08-28 11:23 UTC
