### ISSUE TITLE
Add support for Low Battery Alert

### ISSUE THREAD

**Issue by jchasey** [MindrustUK/Heatmiser-for-home-assistant#54] opened 2020-11-29 18:28 UTC
NeoAirs are battery operated and the API appears to have a LOWBATTERY field, an attribute exposing this would be very useful.

**Comment by DrTree** [comment] 2020-11-29 22:09
Oh gosh yes!
I don't know if this is true of all NeoAir devices but when mine runs out of batteries it enters what I call "anarchy mode" where the heating just turns of randomly.  This, of course, always happens on the hottest day of the year (not even kidding, in 2018 it was 40C outside and the heating decided to come on!!!)

**Comment by jchasey** [comment] 2020-11-30 07:55
I had that issue (but due to poor signal due to thick walls).
Heating comes on for 12 minutes each hour when it is not getting signal from NeoAir.
There is an option (failsafe) to disable this though.

**Comment by ribbal** [comment] 2022-01-07 17:36
I've added a 'low_battery' attribute in this PR https://github.com/MindrustUK/Heatmiser-for-home-assistant/pull/102  Unfortunately, I've not been able to test this because I don't have any battery operated devices.

**Comment by MindrustUK** [comment] 2022-01-08 23:24
I'm closing this issue for now as the original report is pretty old. If the issue is not resolved please open a fresh issue citing this ticket and I'm sure someone will re-investigate.

**Closed by MindrustUK** 2022-01-08 23:24 UTC
