### ISSUE TITLE
Climate "Modes"

### ISSUE THREAD

**Issue by BNWEIN** [MindrustUK/Heatmiser-for-home-assistant#202] opened 2024-10-29 13:16 UTC
Hey Again

So i noticed that the "mode" in a thermostat card is not really relevant (at least in my instance?)

![image](https://github.com/user-attachments/assets/665a63df-9f20-4de5-8f32-aafb6a79411e)

But when the heating is turned on (Set to "Heating") the mode does not change to "Heat", so the colours are wrong. You can see in the screen shot below, the Kitchen is heating, but is showing as blue, because the mode hasnt changed.  Where as my Aircon, which is set to mode "Heat" is orange when on. (Aircon is not a heatmiser thing)

![image](https://github.com/user-attachments/assets/a2f5b8ad-e072-4581-87c6-100356465216)

Hopefully this makes sense?

**Comment by MindrustUK** [comment] 2024-10-30 09:08
@BNWEIN Just to clarify, from your other thread these are NeoAir devices, correct? If so we know these are actively broken and there are plans to support them even though I haven't created a ticket on the board yet. I have one of these as part of my test suite. Keep an eye out for updates adding support for these.

**Comment by BNWEIN** [comment] 2024-10-30 09:20
neoAir V1's

They generally work fine, i can monitor temps, and change temps etc. Its just the colours/modes that are weird.

**Comment by ocrease** [comment] 2024-10-30 17:14
@BNWEIN a new [diagnostics](https://www.home-assistant.io/integrations/diagnostics/) feature has been added to the integration today. If you update to the latest via HACS, you should be able to download the diagnostics data and attach it here (maybe zip it up). This will help with determining how to best support your devices.

**Comment by BNWEIN** [comment] 2024-10-30 17:20
See attached. 

Again, not sure its "Broken".  But when the heating is on, the mode i guess should change to "Heat" and currently doesnt. 

Debug logs attached. 

[config_entry-heatmiserneo-01JB9X30RF6DCHAN1CY6FGNJAQ.json](https://github.com/user-attachments/files/17576660/config_entry-heatmiserneo-01JB9X30RF6DCHAN1CY6FGNJAQ.json)

**Comment by BNWEIN** [comment] 2024-10-30 17:25
Turned the temp up, so the heating is on but mode still shows "mode" even though it says "Heating"

![image](https://github.com/user-attachments/assets/b685cb2c-49fb-4e90-86e3-d8a9058dd553)

If i manually change the mode to "Off", and then turn it back to "Heat", it then turns red (as it should)

![image](https://github.com/user-attachments/assets/94c5f5d4-d72d-48b5-b11e-32ede77896a6)

**Comment by ocrease** [comment] 2024-10-30 17:46
Hi @BNWEIN thanks for the logs. Based on the logs and the code on the main branch I can see why it would be reporting as fan mode. The good news is that I've been doing some changes that I think will address this. If you are interested have a look at #201. It will be a little while before its ready for general use, but once its integrated into the dev branch maybe you can try it out.

**Comment by ocrease** [comment] 2024-10-31 19:32
@BNWEIN the changes I mentioned on #201 are now merged into the dev branch. If you are feeling up to it, would be great if you can try it out and see if your NeoAir works as you expect. Specially since you have one configured in both thermostat and timer mode (the Kitchen?)

Dev branch installation instructions can be found [here](https://github.com/MindrustUK/Heatmiser-for-home-assistant/blob/dev/docs/dev_installation.md)

**Comment by BNWEIN** [comment] 2024-11-01 09:18
Good Morning.

This has now been installed. There is some progress, but its still not right. 

You can see now all of them are orange, even when they are not "Heating".   Really when they are not doing anything, they should be transparent. (same as Gym Aircon and Bedroom Aircon)(These two are not heatmiser)

Orange = Heating
Blue (Never going to be used in my instance) = Cooling
Transparent = Idle / Off 

The two examples to the right (Gym Aircon and Bedroom Aircon) are not heatmiser devices, but they have the correct behaviour. When those devices are not on/heating/cooling etc, they are basically transparent.  When they are "Heating" They go orange, when they are "cooling" they go blue


![image](https://github.com/user-attachments/assets/1127f435-8196-47a3-8792-1a00929d7ecd)

Hope this helps?  

Ill keep dev installed for now, and i am happy to install a new dev version as and when you ask

**Comment by ocrease** [comment] 2024-11-01 17:22
@BNWEIN First of all, thanks for trying out the dev branch!

I believe what you are seeing is as designed by Home Assistant and its not related to this integration

- If the device is "Off", the display is transparent. Your two Aircon devices are showing as Off, so I assume in this state, it doesn't matter what temperature it is in the room, they won't start working.
- If the device is "Idle", but only capable of heating, the bar remain orange (Your Hallway and Upstairs) are in this state. It means the device could start heating if the temperature drops past the trigger point.
- If the device is "Heating", then there is an orange glow added. Your background (which I really like btw) makes it a bit hard to see, but your Kitchen does have the glow. 

If you set one of the thermostats to Off rather than Idle, then the colours would disappear (but I think you rarely want to do that with the Heatmiser devices, Idle makes more sense).

You can play around with dummy thermostats in the [Home Assistant design pages](https://design.home-assistant.io/#lovelace/thermostat-card):

Idle (not heating)
![image](https://github.com/user-attachments/assets/109598ab-6fbb-42f4-b4a2-573854fa909d)

Heating
![image](https://github.com/user-attachments/assets/c8430461-8dd7-40c6-a030-cc3dbca96b6b)

**Comment by BNWEIN** [comment] 2024-11-01 17:37
Ah ok. This makes sense i guess. Like you say, there would never be a time when i turn them off. Happy to close this now and just accept they will always be orange :)

Thanks for looking into it!

**Closed as completed** 2024-11-01 17:37 UTC
Labels: bug
