### ISSUE TITLE
ValueError: time data '24:00' does not match format '%H:%M'

### ISSUE THREAD

**Issue by jamespreedy** [MindrustUK/Heatmiser-for-home-assistant#110] opened 2022-04-20 06:43 UTC
I've recently noticed an error that I get every night around midnight.
I've included it below - is there any further information I can get you to help?
I've also included my System Health below too, to show what I'm running.

Thanks in advance!

`This error originated from a custom integration.

Logger: custom_components.heatmiserneo
Source: custom_components/heatmiserneo/__init__.py:40 
Integration: Heatmiser Neo Climate (documentation) 
First occurred: 12:00:43 am (2 occurrences) 
Last logged: 12:01:13 am

Unexpected error fetching neostat data: time data '24:00' does not match format '%H:%M'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 190, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 150, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/heatmiserneo/__init__.py", line 40, in async_update_data
    _, devices_data = await hub.get_live_data()
  File "/usr/local/lib/python3.9/site-packages/neohubapi/neohub.py", line 401, in get_live_data
    thermostats.append(NeoStat(self, thermostat))
  File "/usr/local/lib/python3.9/site-packages/neohubapi/neostat.py", line 99, in __init__
    _time = datetime.strptime(self.time, "%H:%M")
  File "/usr/local/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '24:00' does not match format '%H:%M'
`

## System Health

version | core-2022.4.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.108
arch | x86_64
timezone | Europe/London

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.24.5
Stage | running
Available Repositories | 1091
Downloaded Repositories | 20

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 1 May 2022, 1:00 am
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | false
remote_server | eu-west-2-0.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.6
-- | --
update_channel | stable
supervisor_version | supervisor-2022.04.0
docker_version | 20.10.9
disk_total | 222.8 GB
disk_used | 17.2 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.3.3), SSH & Web Terminal (10.1.1), Check Home Assistant configuration (3.10.0), Duck DNS (1.14.0), Z-Wave JS to MQTT (0.38.0), Mosquitto broker (6.0.1), InfluxDB (4.4.1), Grafana (7.5.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 1
views | 33
mode | storage

</details>

**Comment by jamespreedy** [comment] 2022-05-21 10:46
We've had a few more HA updates since reporting this, but I'm still seeing this error in my logs.

@MindrustUK - Is there anymore information I can get to help with this or perhaps some logs that might be of use?
Thank you!! 👍🏻

Home Assistant Core 2022.5.5
Home Assistant Supervisor 2022.05.2
Home Assistant OS 8.1
Kernel version 5.15.41
Agent version 1.2.1

**Comment by seeq5** [comment] 2022-06-05 01:26
Also having the same issue since updating. Logs read the same.

**Comment by stikonas** [comment] 2022-07-09 08:37
This is a duplicate of https://gitlab.com/neohubapi/neohubapi/-/issues/8

**Comment by jamespreedy** [comment] 2022-08-04 06:45
Closing as it's a dupe.

**Comment by jamespreedy** [comment] 2022-08-04 06:49
@MindrustUK - stikonas has pointed out that this is a dupe of an issue listed on the neohubapi repo - would you like this to be closed as a dupe?

**Comment by MindrustUK** [comment] 2022-08-04 08:03
as @stikonas Suggested it's a dupe of the issue listed in the neohubapi, as the Heatmiser for home assistant plugin uses neohubapi as it's communication layer it needs to be fixed upstream to have any bearing here. So closing it as a duplicate / non applicable here.

**Closed by MindrustUK** 2022-08-04 08:03 UTC
